server: "hub-cloud.browserstack.com"
common_caps:
  "browserstack.debug": true
  # "browserstack.local": true
browser_caps:
  -
    browser: firefox
  -
    browser: chrome
  -
    browser: safari
  -
    browser: internet explorer
